/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MasterUsersRouteImport } from './routes/master.users'
import { Route as MasterResellersRouteImport } from './routes/master.resellers'
import { Route as MasterOrdersRouteImport } from './routes/master.orders'
import { Route as DriverSignupRouteImport } from './routes/driver.signup'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverDeliveriesRouteImport } from './routes/driver.deliveries'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerBlockedDriversRouteImport } from './routes/customer.blocked-drivers'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppDriversRouteImport } from './routes/app.drivers'
import { Route as CustomerOrderOrderIdRouteImport } from './routes/customer.order.$orderId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MasterRoute,
} as any)
const MasterResellersRoute = MasterResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => MasterRoute,
} as any)
const MasterOrdersRoute = MasterOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MasterRoute,
} as any)
const DriverSignupRoute = DriverSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DriverRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBlockedDriversRoute = CustomerBlockedDriversRouteImport.update({
  id: '/blocked-drivers',
  path: '/blocked-drivers',
  getParentRoute: () => CustomerRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const CustomerOrderOrderIdRoute = CustomerOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/products': typeof AppProductsRoute
  '/customer/blocked-drivers': typeof CustomerBlockedDriversRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/signup': typeof DriverSignupRoute
  '/master/orders': typeof MasterOrdersRoute
  '/master/resellers': typeof MasterResellersRoute
  '/master/users': typeof MasterUsersRoute
  '/app/': typeof AppIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/master/': typeof MasterIndexRoute
  '/customer/order/$orderId': typeof CustomerOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/products': typeof AppProductsRoute
  '/customer/blocked-drivers': typeof CustomerBlockedDriversRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/signup': typeof DriverSignupRoute
  '/master/orders': typeof MasterOrdersRoute
  '/master/resellers': typeof MasterResellersRoute
  '/master/users': typeof MasterUsersRoute
  '/app': typeof AppIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/driver': typeof DriverIndexRoute
  '/master': typeof MasterIndexRoute
  '/customer/order/$orderId': typeof CustomerOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/products': typeof AppProductsRoute
  '/customer/blocked-drivers': typeof CustomerBlockedDriversRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/signup': typeof DriverSignupRoute
  '/master/orders': typeof MasterOrdersRoute
  '/master/resellers': typeof MasterResellersRoute
  '/master/users': typeof MasterUsersRoute
  '/app/': typeof AppIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/master/': typeof MasterIndexRoute
  '/customer/order/$orderId': typeof CustomerOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/customer'
    | '/driver'
    | '/login'
    | '/master'
    | '/reset-password'
    | '/app/drivers'
    | '/app/orders'
    | '/app/products'
    | '/customer/blocked-drivers'
    | '/customer/orders'
    | '/customer/profile'
    | '/driver/deliveries'
    | '/driver/profile'
    | '/driver/signup'
    | '/master/orders'
    | '/master/resellers'
    | '/master/users'
    | '/app/'
    | '/customer/'
    | '/driver/'
    | '/master/'
    | '/customer/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/app/drivers'
    | '/app/orders'
    | '/app/products'
    | '/customer/blocked-drivers'
    | '/customer/orders'
    | '/customer/profile'
    | '/driver/deliveries'
    | '/driver/profile'
    | '/driver/signup'
    | '/master/orders'
    | '/master/resellers'
    | '/master/users'
    | '/app'
    | '/customer'
    | '/driver'
    | '/master'
    | '/customer/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/customer'
    | '/driver'
    | '/login'
    | '/master'
    | '/reset-password'
    | '/app/drivers'
    | '/app/orders'
    | '/app/products'
    | '/customer/blocked-drivers'
    | '/customer/orders'
    | '/customer/profile'
    | '/driver/deliveries'
    | '/driver/profile'
    | '/driver/signup'
    | '/master/orders'
    | '/master/resellers'
    | '/master/users'
    | '/app/'
    | '/customer/'
    | '/driver/'
    | '/master/'
    | '/customer/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/master/users': {
      id: '/master/users'
      path: '/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/resellers': {
      id: '/master/resellers'
      path: '/resellers'
      fullPath: '/master/resellers'
      preLoaderRoute: typeof MasterResellersRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/orders': {
      id: '/master/orders'
      path: '/orders'
      fullPath: '/master/orders'
      preLoaderRoute: typeof MasterOrdersRouteImport
      parentRoute: typeof MasterRoute
    }
    '/driver/signup': {
      id: '/driver/signup'
      path: '/signup'
      fullPath: '/driver/signup'
      preLoaderRoute: typeof DriverSignupRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/deliveries': {
      id: '/driver/deliveries'
      path: '/deliveries'
      fullPath: '/driver/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/blocked-drivers': {
      id: '/customer/blocked-drivers'
      path: '/blocked-drivers'
      fullPath: '/customer/blocked-drivers'
      preLoaderRoute: typeof CustomerBlockedDriversRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers': {
      id: '/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/customer/order/$orderId': {
      id: '/customer/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/customer/order/$orderId'
      preLoaderRoute: typeof CustomerOrderOrderIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AppRouteChildren {
  AppDriversRoute: typeof AppDriversRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDriversRoute: AppDriversRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProductsRoute: AppProductsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CustomerRouteChildren {
  CustomerBlockedDriversRoute: typeof CustomerBlockedDriversRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerOrderOrderIdRoute: typeof CustomerOrderOrderIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBlockedDriversRoute: CustomerBlockedDriversRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerOrderOrderIdRoute: CustomerOrderOrderIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DriverRouteChildren {
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverSignupRoute: typeof DriverSignupRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverSignupRoute: DriverSignupRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface MasterRouteChildren {
  MasterOrdersRoute: typeof MasterOrdersRoute
  MasterResellersRoute: typeof MasterResellersRoute
  MasterUsersRoute: typeof MasterUsersRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterOrdersRoute: MasterOrdersRoute,
  MasterResellersRoute: MasterResellersRoute,
  MasterUsersRoute: MasterUsersRoute,
  MasterIndexRoute: MasterIndexRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
